### ISSUE TITLE
Upgrade http 0.2 to http 1

### ISSUE THREAD

**Issue by neckaros** [ansg191/trakt#50]
Would it be possible to use a more recent version of http? from 0.2 to latest 1.1.0?

Right now we get an error with this crate if using a more recent version in our dependencies:

http::request::Request<Vec<u8>> = req.try_into_http_request(ctx).unwrap...
    |       -------------------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Request<Vec<...>>`, found `Request<_>`

note: `Request<_>` and `Request<Vec<...>>` have similar names, but are actually distinct types

**Comment by ansg191** [comment]
Yes. I've been meaning to upgrade for a while now. I've just been waiting on `reqwest` (which I use for tests) to upgrade.

They recently merged the upgrade into master, but it is blocked on some other [breaking changes](https://github.com/seanmonstar/reqwest/milestone/6).

I'm gonna upgrade it anyway and temporarily change the testing client to `ureq` until 0.12 is released. I'm tired of checking `reqwest`'s status everyday.

This will be upgraded in #51, and a new release will be created after it is merged.

**Comment by neckaros** [comment]
Thank you! I indeed noticed that Reqwest still use 0.2

**Comment by neckaros** [comment]
For information:
On Reqwest side dev has been temp reverted here:
https://github.com/seanmonstar/reqwest/pull/2170

it's available on 0.12-dev
